### ISSUE TITLE
有关pure百度脚本使用后，检索出的内容卡片最左边贴在浏览器界面边缘的问题

### ISSUE THREAD

**Issue by RealMoonHunter** [cworld1/vue-learning#2]
Cword君：
  你好！
  我是pure百度插件的用户，大概从19年起我就开始使用你所制作的插件美化浏览器（非常感谢！）。但是最新版本更新后，该脚本在我所有的设备（包括三星平板的kiwi浏览器上）都会出现搜索结果卡片一边倒，完全靠左贴的情况。不好意思，不是代码小白，我想问一下，是否是pure百度里的：
"/* 搜索结果居中 */",
"/* #container{margin:0 auto;}#content_left {padding-left:0;} */",
出了问题？

如果你能够在百忙之中抽空回答或者更新一下，我会更加感谢。
祝好！
stillopen

**Comment by cworld1** [comment]
已经解决了，麻烦更新一下或者重新安装解决。链接不变：
https://userstyles.org/styles/173673/pure

**Comment by RealMoonHunter** [comment]
太感谢了！祝你学业顺利。
